pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=test-fast
      - check-success=test-slow
      - check-success=docker
      - -draft
      - label!=do-not-merge
    actions:
      merge:
        method: squash
  - name: Auto merge for dependabot
    conditions:
      - author=dependabot[bot]
      - check-success=test-fast
      - check-success=test-slow
      - check-success=docker
    actions:
      merge:
        method: squash
queue_rules:
  - name: main
    merge_method: squash
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body }}

      Approved by: @{{ approved_reviews_by | join(', @') }}
    checks_timeout: 1 h
